name: Upload to IPFS
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aquiladev/ipfs-action@v0.1.5
        id: upload-dapps
        with:
          path: ./dapps
          service: pinata
         pinata_api_key: (239212f4721e57d81f8a77a7fd4e7c15f5faa70ebb8f5bf35089ab9dan )
        pinata_secret_api_key: (05817208a645ed6f1b3d609bee1e5d4ecc6ceb324981676f36afeb8bd2d)
          pinataPinName: dapps
          verbose: false
